<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BallastLane.Test.Domain\BallastLane.Test.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\Scripts\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Scripts\%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>
